source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails'         , '4.0.0'
gem 'mysql2'        , '~> 0.3.12'
gem 'sass-rails'    , '~> 4.0.0'
gem 'uglifier'      , '>= 1.3.0'
gem 'coffee-rails'  , '~> 4.0.0'
gem 'jquery-rails'  , '~> 3.0.4'
gem 'turbolinks'    , '~> 1.3.0'
gem 'jbuilder'      , '~> 1.2'

gem "cancan"                 , :git => 'git://github.com/ryanb/cancan.git', :branch => '2.0'
gem 'bootstrap-sass'         , '~> 2.3.2.0'
gem 'carrierwave'            , '~> 0.9.0'
gem 'ckeditor'               , :git => 'https://github.com/gistia/ckeditor'
gem 'country_select'         , '~> 1.2.0'
gem 'devise'                 , '~> 3.0.1'
gem 'enumerate_it'           , '~> 1.2.0'
gem 'foreigner'              , '~> 1.5.0'
gem 'i18n_alchemy'           , :git => 'https://github.com/carlosantoniodasilva/i18n_alchemy'
gem 'jquery-turbolinks'      , '~> 1.0.0'
gem 'kaminari'               , '~> 0.14.1'
gem 'maildown'               , '~> 1.0.1'
gem 'mini_magick'            , '~> 3.6.0'
gem 'omniauth-facebook'      , '~> 1.4.1'
gem 'omniauth-google-oauth2' , '~> 0.2.1'
gem 'omniauth-twitter'       , '~> 1.0.0'
gem 'sidekiq'                , '~> 2.13.0'
gem 'sinatra'                , '>= 1.3.0', :require => nil
gem 'slim'                   , '>= 1.1.0'
gem 'stripe'                 , :git => 'https://github.com/stripe/stripe-ruby'
gem 'twilio-ruby'            , '~> 3.10.0'
gem 'unicorn'                , '~> 4.6.3'
gem 'whenever'               , '~> 0.8.4'

group :development, :test do
  gem 'dotenv-rails'
  gem 'factory_girl_rails'   , '~> 4.2.1'
  gem 'faker'                , '~> 1.2.0'
  gem 'growl'                , '~> 1.0.3'
  gem 'guard'                , '~> 1.8.2'
  gem 'guard-rspec'          , '~> 3.0.2'
  gem 'pry-meta'
  gem 'jasmine'              , git: 'https://github.com/gistia/jasmine-gem.git'
  gem 'quiet_assets'         , '~> 1.0.2'
  gem 'rspec-rails'          , '~> 2.0'
  gem 'timecop'              , '~> 0.6.3'
end

group :test do
  gem 'shoulda-matchers'
  gem 'vcr'                  , '~> 2.5.0'
  gem 'webmock'              , '~> 1.11.0'
end
