# Base setup

base: &base
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password:
  reconnect: true

# Main database

development:
  <<: *base
  database: iheartpsychics

test:
  <<: *base
  database: iheartpsychics_test

production:
  <<: *base
  database: iheartpsychics
